version: '3'

services:

  cassandra:
    container_name: cassandra
    image: cassandra:latest
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter
    networks:
      - pipeoop

  pyspark-batch-view-service:
    build: ./spark-batch-view-processor
    image: spark-batch-view-processor:new
    environment:
      - CASSANDRA-IP=172.23.0.2
    ports:
      - 8888:8888
    networks:
      - pipeoop
    depends_on:
      - cassandra

volumes:
  cassandra_data:
    driver: local

networks:
  pipeoop: