version: '3'

services:

  cassandra:
    container_name: cassandra
    image: cassandra:latest
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter
    networks:
      - pipeoop
    volumes:
      - 'cassandra_data:/msg'

  pyspark-batch-view-service:
    build: ./spark-batch-view-processor
    image: spark-batch-view-processor:new
    environment:
      - CASSANDRA-IP=cassandra
    ports:
      - 8888:8888
    networks:
      - pipeoop
    links:
      - cassandra
    depends_on:
      - cassandra

  zeppelin:
    container_name: zeppelin
    image: xemuliam/zeppelin:latest
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./notebook:/opt/zeppelin/notebook
    environment:
      ZEPPELIN_PORT: 8080
      ZEPPELIN_JAVA_OPTS: >-
        -Dspark.driver.memory=1g
        -Dspark.executor.memory=2g
      SPARK_SUBMIT_OPTIONS: >-
        --conf spark.driver.host=localhost
        --conf spark.driver.port=8081
    depends_on:
      - cassandra
    links:
      - cassandra
    networks:
      - pipeoop

volumes:
  cassandra_data:
    driver: local

networks:
  pipeoop: