version: '3'

services:

  machine-engine-db:
    image: mysql:5.7
    ports:
      - "13306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: msg
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - machine-db:/var/lib/mysql
      - ./mysql-machine-generator/mysqld.cnf:/etc/conf.d
    networks:
      - machine-engine

  machine-engine-generator:
    build: ./machine-generator
    image: machine-engine-generator:new
    restart: on-failure
    environment:
      TIME_PRINTING: 0
    ports:
      - "3052:3052"
    networks:
      - machine-engine
    depends_on:
      - machine-engine-db
    links:
      - machine-engine-db:mysql

volumes:
  machine-db:

networks:
  machine-engine: