version: '3'

services:

  mosquitto:
    image: eclipse-mosquitto
    restart: always
    hostname: mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"

  proxy-mqtt-service:
    build:
      context: ./proxy-mqtt-service
      dockerfile: Dockerfile
    image: proxy-mqtt-service:new
    container_name: proxy-mqtt
    network_mode: "host"
    depends_on:
      - mosquitto